litellm_settings:
  drop_params: True
  set_verbose: False
  vertex_project: "<YOUR PROJECT ID>"
  vertex_location: "us-central1"

general_settings: 
  master_key: sk-1234

model_list:
  - model_name: gemini-1.0-pro-001
    litellm_params:
      model: vertex_ai/gemini-1.0-pro-001
      temperature: 0.5
      safety_settings:
      - category: HARM_CATEGORY_HARASSMENT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_HATE_SPEECH
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_DANGEROUS_CONTENT
        threshold: BLOCK_NONE      
  - model_name: gemini-1.0-pro-002
    litellm_params:
      model: vertex_ai/gemini-1.0-pro-002
      temperature: 0.5
      safety_settings:
      - category: HARM_CATEGORY_HARASSMENT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_HATE_SPEECH
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_DANGEROUS_CONTENT
        threshold: BLOCK_NONE
  - model_name: gemini-pro-1.5
    litellm_params:
      model: vertex_ai/gemini-1.5-pro-preview-0409
      temperature: 0.5
      safety_settings:
      - category: HARM_CATEGORY_HARASSMENT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_HATE_SPEECH
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
        threshold: BLOCK_NONE
      - category: HARM_CATEGORY_DANGEROUS_CONTENT
        threshold: BLOCK_NONE
