apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: litellm/litellm:v1.35.5
        args: ["--config", "/app/proxy_server_config.yaml"]
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: config-volume
          mountPath: /app/proxy_server_config.yaml
          subPath: config.yaml
      serviceAccountName: k8s-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
      affinity: # 1 pod 1 node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - litellm
            topologyKey: kubernetes.io/hostname
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: litellm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: litellm
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60