apiVersion: v1
kind: Service
metadata:
  name: litellm-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: litellm
  type: LoadBalancer
  loadBalancerSourceRanges: [0.0.0.0/0, 123.123.123.123/32]